CarDealershipMastery/CarDealershipMastery/CarDealership/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarDealership.Data.ADO;
using CarDealership.Data.Factories;
using CarDealership.Models.Tables;

namespace CarDealership.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var model = CarRepositoryFactory.GetRepository().GetRecent();
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact(string vin)
        {
            var model = new Contact();

            ViewBag.Message = vin;

            return View();
        }

    }
}

CarDealershipMastery/CarDealershipMastery/CarDealership/Controllers/InventoryController.cs
using CarDealership.Data.Factories;
using CarDealership.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Controllers
{
    /// <summary>
    /// Represents the logic for Inventory Reports.
    /// </summary>
    public class InventoryController : Controller
    {
        // GET: Inventory
        public ActionResult Details(int id)
        {
            var repo = CarRepositoryFactory.GetRepository();
            var model = repo.GetDetails(id);

            return View(model);
        }



        public ActionResult Search()
        {
            CarViewModel carViewModel = new CarViewModel();

            var carRepo = CarRepositoryFactory.GetRepository();

            var carList = carRepo.GetAllCars();

            List<CarViewModel> carVMList = carList.Select(car => new CarViewModel
            {
                CarId = car.CarId,
                Year = car.Year,
                MakeType = car.MakeType,
                ModelType = car.ModelType,
                Style = car.Style,
                TransmissionType = car.TransmissionType,
                ColorName = car.ColorName,
                InteriorColor = car.InteriorColor,
                Milage = car.Milage,
                VIN = car.VIN,
                SalePrice = car.SalePrice,
                MSRP = car.MSRP,
                UploadedPicture = car.UploadedPicture
            }).ToList();

            return View(carVMList);
        }
    }
}

CarDealershipMastery/CarDealershipMastery/CarDealership/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CarDealershipMastery/CarDealershipMastery/CarDealership/Views/Home/Contact.cshtml
@model CarDealership.Models.Tables.Contact
@{
    ViewBag.Title = "Contact";
}

<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6">
        <h2>@ViewBag.Title</h2>
        <h5>Ask about Vehicle with VIN: @ViewBag.Message</h5>
        @using (Html.BeginForm("Index", "Home", FormMethod.Get, new { enctype = "multipart/form-data"}))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ContactId)
            <label>FullName</label>
            <div class="form-group col-25">
                @Html.TextBoxFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <label>Email</label>
            <div class="form-group col-25">
                @Html.TextBoxFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>

            <label>Phone</label>
            <div class="form-group col-25">
                @Html.TextBoxFor(model => model.Phone)
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>

            <label>Message</label>
            <div class="form-group col-25">
                @Html.TextAreaFor(model => model.Message)
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
            <button id="btnContact" class="btn btn-primary">Send</button>
        }
    </div>
</div>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CarDealershipMastery/CarDealershipMastery/CarDealership/Views/Home/Index.cshtml
@model IEnumerable<CarDealership.Models.Queries.CarItem>
@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    <div class="jumbotron">
        <h1>BIG HUGE SALES!!!</h1>
        <p class="lead">supporting test and disclaimers.</p>
    </div>

    <h2 style="margin-bottom: 2em">Featured Vehicles</h2>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">     
        @foreach (var car in Model)
        {
            <div class="col" style="text-align: center">
                <img src="@Url.Content("~/Images/" + car.UploadedPicture)" />
                <p><strong>@car.Year @car.MakeType @car.ModelType</strong></p>
                <p><strong>@car.SalePrice</strong></p>
                <p>@Html.ActionLink("view details", "Details", "Inventory", new { id = car.CarId }, null)</p>
            </div>
        }
    </div>
</div>